config/routes.rb
SCPX::Application.routes.draw do
  get "messages/index"
  get "messages/show"
  resources :tags
  resources :namespaces
  resources :invites
  resources :users do
    resources :warnings
  end
  resources :sessions
  resources :password_resets
  namespace :admin do
    get :warnings
  end

  resources :notifications, only: [:index, :show, :destroy]
  post '/notifications/read_all' => 'notifications#read_all', as: :read_all_notifications
  post '/notifications/destroy_read' => 'notifications#destroy_read', as: :destroy_read_notifications

  get '/edits' => 'main#edits', as: :recent_edits
  get '/new_pages' => 'main#new_pages', as: :new_pages
  get '/comments' => 'main#comments', as: :recent_comments
  get '/inbox' => 'main#inbox', as: :inbox

  get 'registration', to: 'users#new', as: 'registration'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  constraints subdomain: /^[A-Za-z0-9-]+$/ do
    get '/' => 'namespaces#show'
    get '/pages' => 'pages#index'
    post '/pages' => 'pages#create'
    resources :pages, path: ''
    resources :pages, path: '' do
      resources :versions, only: [:index, :show] do
        get 'rollback', on: :member
        get 'diff', on: :collection
      end
      resources :comments
      resources :votes, only: [:index, :create, :update, :destroy]
    end
  end

  get '/' => 'namespaces#show'
  get '/pages' => 'pages#index'
  match 'api/markdown', to: 'main#markdown_preview', via: [:get, :post], as: :markdown_preview
  resources :messages
  post '/pages' => 'pages#create'
  resources :pages, path: '' do
    resources :versions, only: [:index, :show] do
      get 'rollback', on: :member
      get 'diff', on: :collection
    end
    resources :comments
    resources :votes, only: [:index, :create, :update, :destroy]
  end

  root to: 'namespaces#show'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :check_auth, except: :index

  def edits
    @pages = @namespace.pages.accessible_by(current_ability, :show).paginate(per_page: 30, page: params[:page]).order('updated_at DESC')
  end

  def new_pages
    @pages = @namespace.pages.accessible_by(current_ability, :show).paginate(per_page: 30, page: params[:page]).order('created_at DESC')
  end

  def comments
    @pages = @namespace.pages.accessible_by(current_ability, :show).where( 'namespace_id <> ?', inbox_namespace.id ).order('created_at DESC')
    @comments = []
    @pages.each do |page|
      @comments = @comments + page.comments
    end
    @comments = @comments.sort_by(&:created_at).reverse.paginate(per_page: 30, page: params[:page])
  end

  def inbox
    @pages = Page.accessible_by(current_ability, :show).where( namespace_id: inbox_namespace.id )
    @comments = []
    @pages.each do |page|
      @comments = @comments + page.comments
    end
    @comments = @comments.sort_by(&:created_at).reverse.paginate(per_page: 30, page: params[:page])
  end

  def markdown_preview
    content = params[:content] || ''
    result = MarkdownParser.new(content).to_html.html_safe
    render text: result, layout: false
  end


  private

    def check_auth
      redirect_to(root_url, alert: 'Auth requested') unless current_user
    end

    def inbox_namespace
      @inbox_namesace ||= Namespace.find_by_name! 'inbox'
    end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_body.slim
h2#page_title = @title
div#page-content.hyphenate = markdown @content

app/views/main/comments.html.slim
- title t('.title')

div
  ul
  - @comments.each do |comment|
    li
      =' link_to comment.user.username, comment.user
      =' link_to t('.commented'), ( page_comments_url( comment.page, subdomain: get_subdomain( comment.page.namespace.name ) ) + "#msg#{comment.id}")
      =' link_to comment.page.title, page_url( comment.page, subdomain: get_subdomain( comment.page.namespace.name ) )
      = l( comment.created_at, format: :timestamp )

  p = will_paginate @comments, renderer: BootstrapPagination::Rails

app/views/main/edits.html.slim
- title 'Recent edits'

div
  ul
    - @pages.each do |page|
      li
        =' link_to page.title, page_versions_url( page, subdomain: get_subdomain( page.namespace.name ) )
        =' page.updated_at
        =' t('.by')
        = link_to page.originator, user_path( page.originator )

  p = will_paginate @pages, renderer: BootstrapPagination::Rails

app/views/main/inbox.html.slim
- title t('.title')

- if can? :create, Page
  div.right-align
    = link_to t('.new_page'), new_page_path( subdomain: 'inbox' ), class: 'btn btn-mini'

div.control-group
  label.control-label
    a class="local-action" data-toggle="collapse" data-target="#inbox_pages" = t('.all_pages')
div#inbox_pages class="collapse"
  ul
    - @pages.each do |page|
      li
        =' link_to page.title, page_path(page)
        = t('.edit_message', user: link_to( page.originator, user_path( page.originator ) ), time: l( page.updated_at, format: :timestamp ) ).html_safe

div.clear

div.well
  h3 = t('.all_comments')
  ul
  - @comments.each do |comment|
    li
      =' link_to comment.user.username, comment.user
      =' link_to t('.commented'), (page_comments_path(comment.page) + "#msg#{comment.id}")
      =' link_to comment.page.title, page_path(comment.page)
      = l( comment.created_at, format: :timestamp )

  p = will_paginate @comments, renderer: BootstrapPagination::Rails

app/views/main/new_pages.html.slim
- title 'New pages'

div
  ul
    - @pages.each do |page|
      li
        =' link_to page.title, page_url(page, subdomain: page.namespace.name)
        =' "(#{ page.updated_at })"
        =' 'by'
        = link_to page.originator, user_path(page.originator)


  p = will_paginate @pages, renderer: BootstrapPagination::Rails