config/routes.rb
SCPX::Application.routes.draw do
  get "messages/index"
  get "messages/show"
  resources :tags
  resources :namespaces
  resources :invites
  resources :users do
    resources :warnings
  end
  resources :sessions
  resources :password_resets
  namespace :admin do
    get :warnings
  end

  resources :notifications, only: [:index, :show, :destroy]
  post '/notifications/read_all' => 'notifications#read_all', as: :read_all_notifications
  post '/notifications/destroy_read' => 'notifications#destroy_read', as: :destroy_read_notifications

  get '/edits' => 'main#edits', as: :recent_edits
  get '/new_pages' => 'main#new_pages', as: :new_pages
  get '/comments' => 'main#comments', as: :recent_comments
  get '/inbox' => 'main#inbox', as: :inbox

  get 'registration', to: 'users#new', as: 'registration'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  constraints subdomain: /^[A-Za-z0-9-]+$/ do
    get '/' => 'namespaces#show'
    get '/pages' => 'pages#index'
    post '/pages' => 'pages#create'
    resources :pages, path: ''
    resources :pages, path: '' do
      resources :versions, only: [:index, :show] do
        get 'rollback', on: :member
        get 'diff', on: :collection
      end
      resources :comments
      resources :votes, only: [:index, :create, :update, :destroy]
    end
  end

  get '/' => 'namespaces#show'
  get '/pages' => 'pages#index'
  match 'api/markdown', to: 'main#markdown_preview', via: [:get, :post], as: :markdown_preview
  resources :messages
  post '/pages' => 'pages#create'
  resources :pages, path: '' do
    resources :versions, only: [:index, :show] do
      get 'rollback', on: :member
      get 'diff', on: :collection
    end
    resources :comments
    resources :votes, only: [:index, :create, :update, :destroy]
  end

  root to: 'namespaces#show'
end

app/models/warning.rb
class Warning < ActiveRecord::Base
  belongs_to :user

  def staffer
    @staffer ||= User.find staffer_id
  end
end

app/controllers/warnings_controller.rb
class WarningsController < ApplicationController
  before_action :load_user
  before_action :set_warning, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /warnings
  # GET /warnings.json
  def index
    @warnings = @user.warnings.all
  end

  # GET /warnings/1
  # GET /warnings/1.json
  def show
  end

  # GET /warnings/new
  def new
    @warning = @user.warnings.build
  end

  # GET /warnings/1/edit
  def edit
  end

  # POST /warnings
  # POST /warnings.json
  def create
    @warning = @user.warnings.build(warning_params.merge(staffer_id: current_user.id, user_id: @user.id))

    respond_to do |format|
      if @warning.save
        format.html { redirect_to [@user, @warning], notice: 'Warning was successfully created.' }
        format.json { render action: 'show', status: :created, location: @warning }
      else
        format.html { render action: 'new' }
        format.json { render json: @warning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warnings/1
  # PATCH/PUT /warnings/1.json
  def update
    respond_to do |format|
      if @warning.update(warning_params)
        format.html { redirect_to [@user, @warning], notice: 'Warning was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @warning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warnings/1
  # DELETE /warnings/1.json
  def destroy
    @warning.destroy
    respond_to do |format|
      format.html { redirect_to warnings_url }
      format.json { head :no_content }
    end
  end

  private
    def load_user
      @user = User.find_by_username params[:user_id]
    end

    def set_warning
      @warning = @user.warnings.find(params[:id])
    end

    def warning_params
      params.require(:warning).permit(:description)
    end
end

app/helpers/warnings_helper.rb
module WarningsHelper
end

app/views/warnings/_form.html.slim
= simple_form_for([@user, @warning], html: { class: 'form-horizontal' }) do |f|
  legend = content_for :title
  = f.error_notification

  .inputs
    = f.input :description, as: :text, input_html: { class: 'content_textarea' }
  .form-actions
    = f.button :submit, "Add warning"

app/views/warnings/edit.html.slim
- title 'Edit warning', show_title = false

== render 'form'

= link_to 'Back to the warnings', user_warnings_path(@user), class: 'btn btn-mini'

app/views/warnings/index.html.slim
- title "#{@user.display_name} warnings"

div.top-tools = link_to "Back to the user", @user, class: 'btn btn-mini'

table.table
  tr
    th Description
    th Staffer
    th
    th
    th

  - @warnings.each do |warning|
    tr
      td = truncate(warning.description, length: 30)
      td = link_to warning.staffer.display_name, warning.staffer
      td = link_to 'Show', user_warning_path(@user, warning)
      td = link_to 'Edit', edit_user_warning_path(@user, warning)
      td = link_to 'Destroy', user_warning_path(@user, warning), :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Warning', new_user_warning_path(@user), class: 'btn btn-info'

app/views/warnings/new.html.slim
- title 'New warning', show_title = false

== render 'form'

= link_to 'Back', user_warnings_path(@user)

app/views/warnings/show.html.slim
- title "#{@user.display_name} warning", show_title = false

p#notice = notice

p
  = link_to "Back to the #{@user.display_name} warnings", user_warnings_path(@user), class: 'btn btn-mini'
  span.pull-right
    = link_to 'Edit', edit_user_warning_path(@user, @warning), class: 'btn btn-mini'
p
  =' markdown @warning.description
p
  ' Staffer:
  = link_to @warning.staffer.display_name, @warning.staffer