config/routes.rb
SCPX::Application.routes.draw do
  get "messages/index"
  get "messages/show"
  resources :tags
  resources :namespaces
  resources :invites
  resources :users do
    resources :warnings
  end
  resources :sessions
  resources :password_resets
  namespace :admin do
    get :warnings
  end

  resources :notifications, only: [:index, :show, :destroy]
  post '/notifications/read_all' => 'notifications#read_all', as: :read_all_notifications
  post '/notifications/destroy_read' => 'notifications#destroy_read', as: :destroy_read_notifications

  get '/edits' => 'main#edits', as: :recent_edits
  get '/new_pages' => 'main#new_pages', as: :new_pages
  get '/comments' => 'main#comments', as: :recent_comments
  get '/inbox' => 'main#inbox', as: :inbox

  get 'registration', to: 'users#new', as: 'registration'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  constraints subdomain: /^[A-Za-z0-9-]+$/ do
    get '/' => 'namespaces#show'
    get '/pages' => 'pages#index'
    post '/pages' => 'pages#create'
    resources :pages, path: ''
    resources :pages, path: '' do
      resources :versions, only: [:index, :show] do
        get 'rollback', on: :member
        get 'diff', on: :collection
      end
      resources :comments
      resources :votes, only: [:index, :create, :update, :destroy]
    end
  end

  get '/' => 'namespaces#show'
  get '/pages' => 'pages#index'
  match 'api/markdown', to: 'main#markdown_preview', via: [:get, :post], as: :markdown_preview
  resources :messages
  post '/pages' => 'pages#create'
  resources :pages, path: '' do
    resources :versions, only: [:index, :show] do
      get 'rollback', on: :member
      get 'diff', on: :collection
    end
    resources :comments
    resources :votes, only: [:index, :create, :update, :destroy]
  end

  root to: 'namespaces#show'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :pages

  validates :name, format: /\A[\wа-яА-Я\d\-\_]*\Z/, uniqueness: { case_sensitive: false }
  before_save { write_attribute(:name, read_attribute(:name).downcase) }

  def to_param
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find_by_name(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find_by_name(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(tag_params[:id])

    respond_to do |format|
      if @tag.update_attributes(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(tag_params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :description)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= simple_form_for @tag, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name, required: true
  = f.input :description, as: :text, input_html: { class: 'content_textarea' }
  div.form-actions
    =' f.button :submit, :class => 'btn-primary'
    =' link_to t('.cancel'), tags_path, :class => 'btn'

app/views/tags/edit.html.slim
- title "#{@tag.name}"

= render :partial => 'form'

app/views/tags/index.html.slim
- title 'Tags'

table.table.table-striped
  thead
    tr
      th

  tbody
    - @tags.each do |tag|
      tr
        td = link_to tag.name, tag

= link_to t('.new'), new_tag_path, class: 'btn' if can? :create, Tag

app/views/tags/new.html.slim
- model_class = Tag
- title t('.title')

= render :partial => 'form'

app/views/tags/show.html.slim
- title "#{@tag.name}"
div.top-tools = link_to t('.back_to_the_tags').html_safe, tags_path
- if can? :edit, @tag
  div.form-actions
    =' link_to t('.edit'), edit_tag_path(@tag), class: 'btn btn-mini'
    =' link_to t('.delete'), @tag, method: 'delete', data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger'

div = markdown @tag.description unless @tag.description.blank?

h4 =' t('.pages')

ul
- @tag.pages.each do |page|
  - if can? :read, page
    li = link_to page.title, page_path(page, subdomain: page.namespace.name)