config/routes.rb
SCPX::Application.routes.draw do
  get "messages/index"
  get "messages/show"
  resources :tags
  resources :namespaces
  resources :invites
  resources :users do
    resources :warnings
  end
  resources :sessions
  resources :password_resets
  namespace :admin do
    get :warnings
  end

  resources :notifications, only: [:index, :show, :destroy]
  post '/notifications/read_all' => 'notifications#read_all', as: :read_all_notifications
  post '/notifications/destroy_read' => 'notifications#destroy_read', as: :destroy_read_notifications

  get '/edits' => 'main#edits', as: :recent_edits
  get '/new_pages' => 'main#new_pages', as: :new_pages
  get '/comments' => 'main#comments', as: :recent_comments
  get '/inbox' => 'main#inbox', as: :inbox

  get 'registration', to: 'users#new', as: 'registration'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  constraints subdomain: /^[A-Za-z0-9-]+$/ do
    get '/' => 'namespaces#show'
    get '/pages' => 'pages#index'
    post '/pages' => 'pages#create'
    resources :pages, path: ''
    resources :pages, path: '' do
      resources :versions, only: [:index, :show] do
        get 'rollback', on: :member
        get 'diff', on: :collection
      end
      resources :comments
      resources :votes, only: [:index, :create, :update, :destroy]
    end
  end

  get '/' => 'namespaces#show'
  get '/pages' => 'pages#index'
  match 'api/markdown', to: 'main#markdown_preview', via: [:get, :post], as: :markdown_preview
  resources :messages
  post '/pages' => 'pages#create'
  resources :pages, path: '' do
    resources :versions, only: [:index, :show] do
      get 'rollback', on: :member
      get 'diff', on: :collection
    end
    resources :comments
    resources :votes, only: [:index, :create, :update, :destroy]
  end

  root to: 'namespaces#show'
end

app/models/version.rb
class Version < ActiveRecord::Base
  def user
    @user ||= User.find user_id
  end

  def originator
    user.username
  end
end

app/controllers/versions_controller.rb
require 'ostruct'

class VersionsController < ApplicationController
  before_filter :load_page

  def index
    authorize! :read, @page
    @versions = @page.versions
  end

  def show
    authorize! :read, @page
    @version = @page.versions.find version_params[:id]
  end

  def rollback
    authorize! :edit, @page
    @version = @page.versions.find version_params[:id]
    redirect_to @page, alert: 'Version not found' unless @version
    @page.title, @page.content = @version.title, @version.content
    @page.commit_message = "Rollback to the version #{version_params[:id]}"
    @page.editor_id = current_user.id
    @page.updated_at = Time.now
    @page.save
    redirect_to page_path(@page), notice: 'Rollback'
  end

  def diff
    authorize! :read, @page
    if version_params[:from] == '0' || version_params[:from].blank?
      @first_version = current_version
    else
      @first_version = Version.find(version_params[:from])
    end

    if version_params[:to] == '0' || version_params[:to].blank?
      @second_version = current_version
    else
      @second_version = Version.find(version_params[:to])
    end
  end

  

  private

  def load_page
    @page = @namespace.pages.find_by_slug "#{@namespace.name}:#{version_params[:page_id]}"
  end

  def current_version
    @current_version ||= OpenStruct.new(
      originator: User.find(@page.versions.last.user_id).username,
      created_at: @page.updated_at,
      object_updated_at: @page.updated_at,
      title: @page.title,
      content: @page.content)
  end

  def version_params
    params.permit(:page_id, :id, :from, :to)
  end
end

app/views/versions/diff.html.slim
- title "Versions diff"
= link_to t('.page').html_safe, page_path(@page)
br
= link_to t('.version').html_safe, page_versions_path(@page)

div.well
  strong
    =' t('.author')
  = link_to @first_version.originator, user_path(@first_version.originator)
  br
  strong
    =' t('.changes')
  = @first_version.commit_message
  br
  strong
    =' t('.date')
  = link_to @first_version.object_updated_at, page_version_path(@page, @first_version)

div.well
  strong
    =' t('.author')
  = link_to @second_version.originator, user_path(@second_version.originator)
  br
  strong
    =' t('.changes')
  = @second_version.commit_message
  br
  strong
    =' t('.date')
  = link_to @second_version.updated_at, page_version_path(@page, @second_version)

div.well
  - Differ.format = :html
  h4 = raw Differ.diff_by_word @first_version.title, @second_version.title
  pre
    = raw Differ.diff_by_word @first_version.content, @second_version.content

app/views/versions/index.html.slim
- title t('.title', page: @page.title)

= link_to t('.page').html_safe, page_path(@page)

- unless @page.versions.last.nil?
  .toggle style='margin-top:15px'
    span.hide_action
      =' t('.hide')
    span.show_action
      =' t('.last_changes')
    span.fold_action
      =' t('.last_changes')
    div.spoiler style="display:none"
      div.diff-area
        - Differ.format = :html
        - last_version = @page.versions.last
        pre
          h4 = raw Differ.diff_by_word @page.title, last_version.title
          = raw Differ.diff_by_word @page.content, last_version.content


h4 =' t('.all_versions')

/* - rev = @versions.count */
form.history-form action=diff_page_versions_path(@page)
  table.table.table-hover.table-striped.table-bordered
    thead
      th =' t('.revision')
      th =' t('.user')
      th =' t('.changes')
      th =' t('.date')
      th =' t('.compare')
    tr.success
      td = t('.current')
      td = link_to @page.originator, user_path(@page.originator)
      td = @page.commit_message
      td = link_to @page.updated_at, page_path(@page)
      td.center-align
        input type="radio" name="from" value=0
        '
        input type="radio" name="to" value=0
    - @versions.reverse.each do |version|
      - if version.nil?
      - else
        tr
          td = version.id
          td = link_to version.originator, user_path(version.originator)
          td = version.commit_message
          td = link_to version.updated_at, page_version_path(@page, version)
          td.center-align
            input type="radio" name="from" value=version.id
            '
            input type="radio" name="to" value=version.id
  div.right-align
    = submit_tag t('.compare'), id: "history-compare-button", class: "btn"

app/views/versions/show.html.slim
- title t('.title', :page => @page.title)
= link_to t('.page').html_safe, page_path(@page)
br
= link_to t('.version').html_safe, page_versions_path(@page)

div.well
  - if can? :edit, @page
    div.right
      = link_to t('.rollback'), rollback_page_version_path(@page, @version), class: 'btn btn-mini', confirm: 'Are you sure?'
  strong
    =' t('.author')
  = link_to @version.originator, user_path(@version.originator)
  br
  strong
    =' t('.changes')
  = @version.commit_message
  br
  strong
    =' t('.date')
  = @version.updated_at

div.well
  h4 = @version.title
  = markdown @version.content

/* div.well.diff-area */
/*   - Differ.format = :html */
/*   - previous_version = @version.previous */
/*   - if previous_version.object != nil */
/*     h4 = raw Differ.diff_by_word @version.reify.title, previous_version.reify.title */
/*     = raw Differ.diff_by_word @version.reify.content, previous_version.reify.content */
/*   - else */
/*     h4 = raw @version.reify.title */
/*     = raw @version.reify.content */